language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements_tests.txt
  - pip install codecov
script: 
  - nosetests --with-coverage --cover-package=open_urls --cover-package=tests --cover-tests
after_success:
  - codecov
