language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements_tests.txt
  - pip install coveralls
script: 
  - nosetests --with-coverage
after_success:
  - coveralls
